apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: studycenter-data
  namespace: studycenter
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-retain

