"""persist related card proposals and bridge notes

Revision ID: 65d07f1027b6
Revises: 9d1efe345f72
Create Date: 2026-09-15 13:12:35.303798
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '65d07f1027b6'
down_revision: Union[str, None] = '9d1efe345f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bridge_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('related_card_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['knowledge_cards.id'], ),
    sa.ForeignKeyConstraint(['related_card_id'], ['knowledge_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('related_card_proposals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('card_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('generated_card_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['knowledge_cards.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('related_card_proposals')
    op.drop_table('bridge_notes')
    # ### end Alembic commands ###
